name: Bottler

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  bottles:
    strategy:
      matrix:
        # Add or remove platforms as needed
        os: [macos-13, macos-14, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        uses: homebrew/actions/setup-homebrew@master

      - name: Build bottle
        run: |
          brew test-bot --only-cleanup-before
          brew test-bot --only-setup
          brew test-bot --only-tap-syntax
          brew test-bot --only-formulae --build-bottle

      - name: Upload bottle artifact
        uses: actions/upload-artifact@v4
        with:
          name: bottles_${{ matrix.os }}
          path: "*.bottle.*"
